# Docker Compose for local development and testing
version: '3.8'

services:
  backend:
    build: ./spotify-recommender
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=music_recommender
      - JWT_SECRET=your-jwt-secret
      - SESSION_SECRET=your-session-secret
    depends_on:
      - mysql
    volumes:
      - ./spotify-recommender/uploads:/app/uploads

  frontend:
    build: ./frontend-spotify-recommender
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=music_recommender
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
