# DigitalOcean App Platform Configuration
name: music-emotion-recommender
services:
- name: backend
  source_dir: /spotify-recommender
  github:
    repo: your-username/musicrecommender
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_USER
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: DB_NAME
    value: ${db.DATABASE}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: SESSION_SECRET
    value: ${SESSION_SECRET}
  - key: SPOTIFY_CLIENT_ID
    value: ${SPOTIFY_CLIENT_ID}
  - key: SPOTIFY_CLIENT_SECRET
    value: ${SPOTIFY_CLIENT_SECRET}
  - key: GOOGLE_CLIENT_ID
    value: ${GOOGLE_CLIENT_ID}
  - key: GOOGLE_CLIENT_SECRET
    value: ${GOOGLE_CLIENT_SECRET}
  - key: GOOGLE_APPLICATION_CREDENTIALS
    value: ${GOOGLE_APPLICATION_CREDENTIALS}
  http_port: 3001

- name: frontend
  source_dir: /frontend-spotify-recommender
  github:
    repo: your-username/musicrecommender
    branch: main
  build_command: npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_API_URL
    value: ${backend.PUBLIC_URL}
  http_port: 3000
  routes:
  - path: /

databases:
- name: db
  engine: MYSQL
  version: "8"
  size: db-s-1vcpu-1gb
